version: '3.7'
services:
  terraform:
    container_name: terraform-container
    build:
      context: .
      dockerfile: ./files/docker/Dockerfile
    volumes:
      - ./terraform:/workspace
      - ./files:/files
    tty: true
    working_dir: /workspace
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}